# node worker.js
# node worker.js

# Go inside container and debug MQ
# sudo docker exec -it rabbitmq /bin/bash
# sudo rabbitmqctl list_queues name messages_ready messages_unacknowledged

# node new_task.js First message.
# node new_task.js Second message..
# node new_task.js Third message...
# node new_task.js Fourth message....
# node new_task.js Fifth message.....

node new_task.js First message.....
node new_task.js Second message.....
node new_task.js Third message.....
node new_task.js Fourth message.....
node new_task.js Fifth message.....